from diffusers import ComponentsManager

from modiff.diffusers_offload import (
    OFFLOAD_MODE_GROUP_CPU,
    OFFLOAD_MODE_GROUP_DISK,
    OFFLOAD_MODE_MODEL_CPU,
    OFFLOAD_MODE_NONE,
    offload_mode_param,
)

from .modular_utils import ModiffPipelineRegistry


MESSAGE_DURATION = 5000
components = ComponentsManager()


# Global singleton registry instance for the package
MODULAR_REGISTRY = ModiffPipelineRegistry()

MODULE_PARSE = [
    "adapters",
    "controlnet",
    "denoise",
    "embeddings",
    "guiders",
    "latents",
    "loaders",
    "schedulers",
    "dynamic_node",
]

SDXL_BLOCKS = [
    "down_blocks.1.attentions.0",
    "down_blocks.1.attentions.1",
    "down_blocks.2.attentions.0",
    "down_blocks.2.attentions.1",
    "mid_block.attentions.0",
    "up_blocks.0.attentions.0",
    "up_blocks.0.attentions.1",
    "up_blocks.0.attentions.2",
    "up_blocks.1.attentions.0",
    "up_blocks.1.attentions.1",
    "up_blocks.1.attentions.2  ",
]

QWEN_IMAGE_BLOCKS = [
    "transformer_blocks.0.attn",
    "transformer_blocks.1.attn",
    "transformer_blocks.2.attn",
    "transformer_blocks.3.attn",
    "transformer_blocks.4.attn",
    "transformer_blocks.5.attn",
    "transformer_blocks.6.attn",
    "transformer_blocks.7.attn",
    "transformer_blocks.8.attn",
    "transformer_blocks.9.attn",
    "transformer_blocks.10.attn",
    "transformer_blocks.11.attn",
    "transformer_blocks.12.attn",
    "transformer_blocks.13.attn",
    "transformer_blocks.14.attn",
    "transformer_blocks.15.attn",
    "transformer_blocks.16.attn",
    "transformer_blocks.17.attn",
    "transformer_blocks.18.attn",
    "transformer_blocks.19.attn",
    "transformer_blocks.20.attn",
    "transformer_blocks.21.attn",
    "transformer_blocks.22.attn",
    "transformer_blocks.23.attn",
    "transformer_blocks.24.attn",
    "transformer_blocks.25.attn",
    "transformer_blocks.26.attn",
    "transformer_blocks.27.attn",
    "transformer_blocks.28.attn",
    "transformer_blocks.29.attn",
    "transformer_blocks.30.attn",
    "transformer_blocks.31.attn",
    "transformer_blocks.32.attn",
    "transformer_blocks.33.attn",
    "transformer_blocks.34.attn",
    "transformer_blocks.35.attn",
    "transformer_blocks.36.attn",
    "transformer_blocks.37.attn",
    "transformer_blocks.38.attn",
    "transformer_blocks.39.attn",
    "transformer_blocks.40.attn",
    "transformer_blocks.41.attn",
    "transformer_blocks.42.attn",
    "transformer_blocks.43.attn",
    "transformer_blocks.44.attn",
    "transformer_blocks.45.attn",
    "transformer_blocks.46.attn",
    "transformer_blocks.47.attn",
    "transformer_blocks.48.attn",
    "transformer_blocks.49.attn",
    "transformer_blocks.50.attn",
    "transformer_blocks.51.attn",
    "transformer_blocks.52.attn",
    "transformer_blocks.53.attn",
    "transformer_blocks.54.attn",
    "transformer_blocks.55.attn",
    "transformer_blocks.56.attn",
    "transformer_blocks.57.attn",
    "transformer_blocks.58.attn",
    "transformer_blocks.59.attn",
]

FLUX_BLOCKS = [
    "transformer_blocks.0.attn",
    "transformer_blocks.1.attn",
    "transformer_blocks.2.attn",
    "transformer_blocks.3.attn",
    "transformer_blocks.4.attn",
    "transformer_blocks.5.attn",
    "transformer_blocks.6.attn",
    "transformer_blocks.7.attn",
    "transformer_blocks.8.attn",
    "transformer_blocks.9.attn",
    "transformer_blocks.10.attn",
    "transformer_blocks.11.attn",
    "transformer_blocks.12.attn",
    "transformer_blocks.13.attn",
    "transformer_blocks.14.attn",
    "transformer_blocks.15.attn",
    "transformer_blocks.16.attn",
    "transformer_blocks.17.attn",
    "transformer_blocks.18.attn",
    "single_transformer_blocks.0.attn",
    "single_transformer_blocks.1.attn",
    "single_transformer_blocks.2.attn",
    "single_transformer_blocks.3.attn",
    "single_transformer_blocks.4.attn",
    "single_transformer_blocks.5.attn",
    "single_transformer_blocks.6.attn",
    "single_transformer_blocks.7.attn",
    "single_transformer_blocks.8.attn",
    "single_transformer_blocks.9.attn",
    "single_transformer_blocks.10.attn",
    "single_transformer_blocks.11.attn",
    "single_transformer_blocks.12.attn",
    "single_transformer_blocks.13.attn",
    "single_transformer_blocks.14.attn",
    "single_transformer_blocks.15.attn",
    "single_transformer_blocks.16.attn",
    "single_transformer_blocks.17.attn",
    "single_transformer_blocks.18.attn",
    "single_transformer_blocks.19.attn",
    "single_transformer_blocks.20.attn",
    "single_transformer_blocks.21.attn",
    "single_transformer_blocks.22.attn",
    "single_transformer_blocks.23.attn",
    "single_transformer_blocks.24.attn",
    "single_transformer_blocks.25.attn",
    "single_transformer_blocks.26.attn",
    "single_transformer_blocks.27.attn",
    "single_transformer_blocks.28.attn",
    "single_transformer_blocks.29.attn",
    "single_transformer_blocks.30.attn",
    "single_transformer_blocks.31.attn",
    "single_transformer_blocks.32.attn",
    "single_transformer_blocks.33.attn",
    "single_transformer_blocks.34.attn",
    "single_transformer_blocks.35.attn",
    "single_transformer_blocks.36.attn",
    "single_transformer_blocks.37.attn",
]
