"""Torch-free public constants for Diffusers residency planning."""

OFFLOAD_MODE_NONE = "none"
OFFLOAD_MODE_MODEL_CPU = "model_cpu"
OFFLOAD_MODE_SEQUENTIAL_CPU = "sequential_cpu"
OFFLOAD_MODE_GROUP_CPU = "group_cpu"
OFFLOAD_MODE_GROUP_DISK = "group_disk"
OFFLOAD_MODE_AUTO_CPU = "auto_cpu"

OFFLOAD_MODE_OPTIONS = [
    OFFLOAD_MODE_NONE,
    OFFLOAD_MODE_MODEL_CPU,
    OFFLOAD_MODE_SEQUENTIAL_CPU,
    OFFLOAD_MODE_GROUP_CPU,
    OFFLOAD_MODE_GROUP_DISK,
]
OFFLOAD_MODE_LEGACY_OPTIONS = [OFFLOAD_MODE_AUTO_CPU, *OFFLOAD_MODE_OPTIONS]
